remote_theme: xdanger/jekyll-theme-notion
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Recipe Rating Analysis
description: Breaking down what makes a good recipe